name: merchendice

services:
  merchendice:
    build:
      context: .
    image: merchendice:latest
    container_name: merchendice
    restart: unless-stopped
    ports:
      - "127.0.0.1:82:8080"
